import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AlertMessageProvider } from "@/contexts/AlertMessageContext";
import AppWrapper from "@/components/AppWrapper";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <main className="w-[33%] mx-auto relative">
          <AppWrapper>
            <AlertMessageProvider position="bottom-right">
              {children}
            </AlertMessageProvider>
          </AppWrapper>
        </main>
      </body>
    </html>
  );
}
